version: '3'
services:
  web:
    image: basic_calendly
    build: .
    command: python main.py
    ports:
      - "5000:5000"
    depends_on: 
      - "mongo"

  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
  
